version: '3.9'

services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
        AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
        NODE_ENV: production
        DATABASE_URL: ${DATABASE_URL}
        OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
    volumes:
      - ./public/uploads:/app/public/uploads
